#pragma once

#include <Errnos.h>
#include <Syscall.h>

int64_t __Handle__Read(uint64_t __Fd__,
                       uint64_t __Buf__,
                       uint64_t __Len__,
                       uint64_t __U4__,
                       uint64_t __U5__,
                       uint64_t __U6__);
int64_t __Handle__Write(uint64_t __Fd__,
                        uint64_t __Buf__,
                        uint64_t __Len__,
                        uint64_t __U4__,
                        uint64_t __U5__,
                        uint64_t __U6__);
int64_t __Handle__Writev(uint64_t __Fd__,
                         uint64_t __IovPtr__,
                         uint64_t __IovCnt__,
                         uint64_t __U4__,
                         uint64_t __U5__,
                         uint64_t __U6__);
int64_t __Handle__Readv(uint64_t __Fd__,
                        uint64_t __IovPtr__,
                        uint64_t __IovCnt__,
                        uint64_t __U4__,
                        uint64_t __U5__,
                        uint64_t __U6__);
int64_t __Handle__Open(uint64_t __Path__,
                       uint64_t __Flags__,
                       uint64_t __Mode__,
                       uint64_t __U4__,
                       uint64_t __U5__,
                       uint64_t __U6__);
int64_t __Handle__Close(uint64_t __Fd__,
                        uint64_t __U2__,
                        uint64_t __U3__,
                        uint64_t __U4__,
                        uint64_t __U5__,
                        uint64_t __U6__);
int64_t __Handle__Stat(uint64_t __Path__,
                       uint64_t __OutStat__,
                       uint64_t __U3__,
                       uint64_t __U4__,
                       uint64_t __U5__,
                       uint64_t __U6__);
int64_t __Handle__Fstat(uint64_t __Fd__,
                        uint64_t __OutStat__,
                        uint64_t __U3__,
                        uint64_t __U4__,
                        uint64_t __U5__,
                        uint64_t __U6__);
int64_t __Handle__Lseek(uint64_t __Fd__,
                        uint64_t __Off__,
                        uint64_t __Whence__,
                        uint64_t __U4__,
                        uint64_t __U5__,
                        uint64_t __U6__);
int64_t __Handle__Ioctl(uint64_t __Fd__,
                        uint64_t __Cmd__,
                        uint64_t __Arg__,
                        uint64_t __U4__,
                        uint64_t __U5__,
                        uint64_t __U6__);
int64_t __Handle__Access(uint64_t __Path__,
                         uint64_t __Mode__,
                         uint64_t __U3__,
                         uint64_t __U4__,
                         uint64_t __U5__,
                         uint64_t __U6__);
int64_t __Handle__Pipe(uint64_t __PipefdPtr__,
                       uint64_t __U2__,
                       uint64_t __U3__,
                       uint64_t __U4__,
                       uint64_t __U5__,
                       uint64_t __U6__);
int64_t __Handle__Dup(uint64_t __Fd__,
                      uint64_t __U2__,
                      uint64_t __U3__,
                      uint64_t __U4__,
                      uint64_t __U5__,
                      uint64_t __U6__);
int64_t __Handle__Dup2(uint64_t __OldFd__,
                       uint64_t __NewFd__,
                       uint64_t __U3__,
                       uint64_t __U4__,
                       uint64_t __U5__,
                       uint64_t __U6__);
int64_t __Handle__Mkdir(uint64_t __Path__,
                        uint64_t __Mode__,
                        uint64_t __U3__,
                        uint64_t __U4__,
                        uint64_t __U5__,
                        uint64_t __U6__);
int64_t __Handle__Rmdir(uint64_t __Path__,
                        uint64_t __U2__,
                        uint64_t __U3__,
                        uint64_t __U4__,
                        uint64_t __U5__,
                        uint64_t __U6__);
int64_t __Handle__Unlink(uint64_t __Path__,
                         uint64_t __U2__,
                         uint64_t __U3__,
                         uint64_t __U4__,
                         uint64_t __U5__,
                         uint64_t __U6__);
int64_t __Handle__Rename(uint64_t __Old__,
                         uint64_t __New__,
                         uint64_t __U3__,
                         uint64_t __U4__,
                         uint64_t __U5__,
                         uint64_t __U6__);
int64_t __Handle__SchedYield(uint64_t __U1__,
                             uint64_t __U2__,
                             uint64_t __U3__,
                             uint64_t __U4__,
                             uint64_t __U5__,
                             uint64_t __U6__);
int64_t __Handle__Nanosleep(uint64_t __ReqPtr__,
                            uint64_t __RemPtr__,
                            uint64_t __U3__,
                            uint64_t __U4__,
                            uint64_t __U5__,
                            uint64_t __U6__);
int64_t __Handle__Getpid(uint64_t __U1__,
                         uint64_t __U2__,
                         uint64_t __U3__,
                         uint64_t __U4__,
                         uint64_t __U5__,
                         uint64_t __U6__);
int64_t __Handle__Getppid(uint64_t __U1__,
                          uint64_t __U2__,
                          uint64_t __U3__,
                          uint64_t __U4__,
                          uint64_t __U5__,
                          uint64_t __U6__);
int64_t __Handle__Gettid(uint64_t __U1__,
                         uint64_t __U2__,
                         uint64_t __U3__,
                         uint64_t __U4__,
                         uint64_t __U5__,
                         uint64_t __U6__);
int64_t __Handle__Fork(uint64_t __U1__,
                       uint64_t __U2__,
                       uint64_t __U3__,
                       uint64_t __U4__,
                       uint64_t __U5__,
                       uint64_t __U6__);
int64_t __Handle__Execve(uint64_t __Path__,
                         uint64_t __Argv__,
                         uint64_t __Envp__,
                         uint64_t __U4__,
                         uint64_t __U5__,
                         uint64_t __U6__);
int64_t __Handle__Exit(uint64_t __Status__,
                       uint64_t __U2__,
                       uint64_t __U3__,
                       uint64_t __U4__,
                       uint64_t __U5__,
                       uint64_t __U6__);
int64_t __Handle__Wait4(uint64_t __Pid__,
                        uint64_t __StatusPtr__,
                        uint64_t __Options__,
                        uint64_t __RusagePtr__,
                        uint64_t __U5__,
                        uint64_t __U6__);
int64_t __Handle__Kill(uint64_t __Pid__,
                       uint64_t __Sig__,
                       uint64_t __U3__,
                       uint64_t __U4__,
                       uint64_t __U5__,
                       uint64_t __U6__);
int64_t __Handle__Getcwd(uint64_t __Buf__,
                         uint64_t __Len__,
                         uint64_t __U3__,
                         uint64_t __U4__,
                         uint64_t __U5__,
                         uint64_t __U6__);
int64_t __Handle__Chdir(uint64_t __Path__,
                        uint64_t __U2__,
                        uint64_t __U3__,
                        uint64_t __U4__,
                        uint64_t __U5__,
                        uint64_t __U6__);
int64_t __Handle__Uname(uint64_t __Buf__,
                        uint64_t __U2__,
                        uint64_t __U3__,
                        uint64_t __U4__,
                        uint64_t __U5__,
                        uint64_t __U6__);
int64_t __Handle__Gettimeofday(uint64_t __Tv__,
                               uint64_t __Tz__,
                               uint64_t __U3__,
                               uint64_t __U4__,
                               uint64_t __U5__,
                               uint64_t __U6__);
int64_t __Handle__Times(uint64_t __TmsPtr__,
                        uint64_t __U2__,
                        uint64_t __U3__,
                        uint64_t __U4__,
                        uint64_t __U5__,
                        uint64_t __U6__);
int64_t __Handle__ClockGettime(uint64_t __ClkId__,
                               uint64_t __Tp__,
                               uint64_t __U3__,
                               uint64_t __U4__,
                               uint64_t __U5__,
                               uint64_t __U6__);
int64_t __Handle__Mmap(uint64_t __Addr__,
                       uint64_t __Len__,
                       uint64_t __Prot__,
                       uint64_t __Flags__,
                       uint64_t __Fd__,
                       uint64_t __Off__);
int64_t __Handle__Munmap(uint64_t __Addr__,
                         uint64_t __Len__,
                         uint64_t __U3__,
                         uint64_t __U4__,
                         uint64_t __U5__,
                         uint64_t __U6__);
int64_t __Handle__Brk(uint64_t __NewBrk__,
                      uint64_t __U2__,
                      uint64_t __U3__,
                      uint64_t __U4__,
                      uint64_t __U5__,
                      uint64_t __U6__);
int64_t __Handle__Select(uint64_t __Nfds__,
                         uint64_t __Readfds__,
                         uint64_t __Writefds__,
                         uint64_t __Exceptfds__,
                         uint64_t __Timeout__,
                         uint64_t __U6__);
